version: '3.4'

services:
  app: 
    build:
      context: ./todolist_client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  api: 
    build:
      context: ./todolist_server
      dockerfile: Dockerfile
    ports:
      - 8080:8080